// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

[Index("CertificationLevel", Name = "IDX_CarClasses_CertificationLevel")]
internal partial class CarClass
{
    [Key]
    public int CarClassID { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string CarClassName { get; set; }

    [Column(TypeName = "decimal(4, 1)")]
    public decimal MaxEngineSize { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string CertificationLevel { get; set; }

    [Column(TypeName = "money")]
    public decimal RaceRentalFee { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("CarClass")]
    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    [ForeignKey("CertificationLevel")]
    [InverseProperty("CarClasses")]
    public virtual Certification CertificationLevelNavigation { get; set; }
}