// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

internal partial class Certification
{
    [Key]
    [StringLength(1)]
    [Unicode(false)]
    public string CertificationLevel { get; set; }

    [Required]
    [StringLength(30)]
    public string Description { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("CertificationLevelNavigation")]
    public virtual ICollection<CarClass> CarClasses { get; set; } = new List<CarClass>();

    [InverseProperty("CertificationLevelNavigation")]
    public virtual ICollection<Member> Members { get; set; } = new List<Member>();

    [InverseProperty("CertificationLevelNavigation")]
    public virtual ICollection<Race> Races { get; set; } = new List<Race>();
}