// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

[Index("PositionID", Name = "IDX_Employees_PositionID")]
internal partial class Employee
{
    [Key]
    public int EmployeeID { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Address { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [StringLength(6)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Phone { get; set; }

    public int PositionID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LoginId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime BirthDate { get; set; }

    [Required]
    [StringLength(9)]
    [Unicode(false)]
    public string SocialInsuranceNumber { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    [InverseProperty("Employee")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [ForeignKey("PositionID")]
    [InverseProperty("Employees")]
    public virtual Position Position { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<ReceiveOrder> ReceiveOrders { get; set; } = new List<ReceiveOrder>();

    [InverseProperty("Employee")]
    public virtual ICollection<SalesCartItem> SalesCartItems { get; set; } = new List<SalesCartItem>();
}