// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

[Index("InvoiceID", Name = "IDX_InvoiceDetails_InvoiceID")]
[Index("ProductID", Name = "IDX_InvoiceDetails_ProductID")]
internal partial class InvoiceDetail
{
    [Key]
    public int InvoiceDetailID { get; set; }

    public int InvoiceID { get; set; }

    public int ProductID { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal? Price { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("InvoiceID")]
    [InverseProperty("InvoiceDetails")]
    public virtual Invoice Invoice { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("InvoiceDetails")]
    public virtual Product Product { get; set; }
}