// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

[Index("EmployeeID", Name = "IDX_Invoices_EmployeeID")]
internal partial class Invoice
{
    [Key]
    public int InvoiceID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InvoiceDate { get; set; }

    public int EmployeeID { get; set; }

    [Column(TypeName = "money")]
    public decimal SubTotal { get; set; }

    [Column(TypeName = "money")]
    public decimal GST { get; set; }

    [Column(TypeName = "money")]
    public decimal? Total { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Invoices")]
    public virtual Employee Employee { get; set; }

    [InverseProperty("Invoice")]
    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();

    [InverseProperty("Invoice")]
    public virtual ICollection<RaceDetail> RaceDetails { get; set; } = new List<RaceDetail>();

    [InverseProperty("Invoice")]
    public virtual ICollection<StoreRefund> StoreRefundInvoices { get; set; } = new List<StoreRefund>();

    [InverseProperty("OriginalInvoice")]
    public virtual ICollection<StoreRefund> StoreRefundOriginalInvoices { get; set; } = new List<StoreRefund>();
}