// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

[Index("CertificationLevel", Name = "IDX_Members_CertificationLevel")]
internal partial class Member
{
    [Key]
    public int MemberID { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Address { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [StringLength(6)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EmailAddress { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime BirthDate { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string CertificationLevel { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    [ForeignKey("CertificationLevel")]
    [InverseProperty("Members")]
    public virtual Certification CertificationLevelNavigation { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<RaceDetail> RaceDetails { get; set; } = new List<RaceDetail>();
}