// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

[Index("ProductID", Name = "IDX_OrderDetail_ProductID")]
[Index("OrderID", Name = "IDX_OrderDetails_OrderID")]
internal partial class OrderDetail
{
    [Key]
    public int OrderDetailID { get; set; }

    public int OrderID { get; set; }

    public int ProductID { get; set; }

    public int Quantity { get; set; }

    public int OrderUnitSize { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal Cost { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("OrderDetails")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("OrderDetails")]
    public virtual Product Product { get; set; }

    [InverseProperty("OrderDetail")]
    public virtual ICollection<ReceiveOrderItem> ReceiveOrderItems { get; set; } = new List<ReceiveOrderItem>();

    [InverseProperty("OrderDetail")]
    public virtual ICollection<ReturnOrderItem> ReturnOrderItems { get; set; } = new List<ReturnOrderItem>();
}