// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

[Index("CarID", Name = "IDX_RaceDetails_CarID")]
[Index("InvoiceID", Name = "IDX_RaceDetails_InvoiceID")]
[Index("MemberID", Name = "IDX_RaceDetails_MemberID")]
[Index("PenaltyID", Name = "IDX_RaceDetails_PenaltyID")]
[Index("RaceID", Name = "IDX_RaceDetails_RaceID")]
internal partial class RaceDetail
{
    [Key]
    public int RaceDetailID { get; set; }

    public int RaceID { get; set; }

    public int? CarID { get; set; }

    public int MemberID { get; set; }

    public int? Place { get; set; }

    public TimeSpan? RunTime { get; set; }

    public int? PenaltyID { get; set; }

    [StringLength(1048)]
    public string Comment { get; set; }

    public int? InvoiceID { get; set; }

    [Column(TypeName = "money")]
    public decimal RaceFee { get; set; }

    [Column(TypeName = "money")]
    public decimal RentalFee { get; set; }

    public bool Refund { get; set; }

    [StringLength(150)]
    public string RefundReason { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("CarID")]
    [InverseProperty("RaceDetails")]
    public virtual Car Car { get; set; }

    [ForeignKey("InvoiceID")]
    [InverseProperty("RaceDetails")]
    public virtual Invoice Invoice { get; set; }

    [ForeignKey("MemberID")]
    [InverseProperty("RaceDetails")]
    public virtual Member Member { get; set; }

    [ForeignKey("PenaltyID")]
    [InverseProperty("RaceDetails")]
    public virtual RacePenalty Penalty { get; set; }

    [ForeignKey("RaceID")]
    [InverseProperty("RaceDetails")]
    public virtual Race Race { get; set; }
}