// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

[Index("OrderDetailID", Name = "IDX_ReceiveOrderItems_OrderDetailID")]
[Index("ReceiveOrderID", Name = "IDX_ReceiveOrderItems_ReceiveOrderID")]
internal partial class ReceiveOrderItem
{
    [Key]
    public int ReceiveOrderItemID { get; set; }

    public int ReceiveOrderID { get; set; }

    public int OrderDetailID { get; set; }

    public int ItemQuantity { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("OrderDetailID")]
    [InverseProperty("ReceiveOrderItems")]
    public virtual OrderDetail OrderDetail { get; set; }

    [ForeignKey("ReceiveOrderID")]
    [InverseProperty("ReceiveOrderItems")]
    public virtual ReceiveOrder ReceiveOrder { get; set; }
}