// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

[Index("OrderDetailID", Name = "IDX_ReturnOrderItems_OrderDetailID")]
[Index("ReceiveOrderID", Name = "IDX_ReturnOrderItems_ReceiveOrderID")]
internal partial class ReturnOrderItem
{
    [Key]
    public int ReturnOrderItemID { get; set; }

    public int ReceiveOrderID { get; set; }

    public int? OrderDetailID { get; set; }

    [StringLength(50)]
    public string UnOrderedItem { get; set; }

    public int ItemQuantity { get; set; }

    [StringLength(100)]
    public string Comment { get; set; }

    [StringLength(25)]
    public string VendorProductID { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("OrderDetailID")]
    [InverseProperty("ReturnOrderItems")]
    public virtual OrderDetail OrderDetail { get; set; }

    [ForeignKey("ReceiveOrderID")]
    [InverseProperty("ReturnOrderItems")]
    public virtual ReceiveOrder ReceiveOrder { get; set; }
}