// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

[PrimaryKey("ProductID", "EmployeeID")]
internal partial class SalesCartItem
{
    [Key]
    public int EmployeeID { get; set; }

    [Key]
    public int ProductID { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal UnitPrice { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("SalesCartItems")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("SalesCartItems")]
    public virtual Product Product { get; set; }
}