// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

internal partial class UnOrderedItem
{
    [Key]
    public int ItemID { get; set; }

    public int OrderID { get; set; }

    [Required]
    [StringLength(50)]
    public string ItemName { get; set; }

    [Required]
    [StringLength(25)]
    public string VendorProductID { get; set; }

    public int Quantity { get; set; }

    public bool RemoveFromViewFlag { get; set; }
}