// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERaceLibrary.Entities;

internal partial class Vendor
{
    [Key]
    public int VendorID { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Address { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [StringLength(6)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Phone { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Contact { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("Vendor")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [InverseProperty("Vendor")]
    public virtual ICollection<VendorCatalog> VendorCatalogs { get; set; } = new List<VendorCatalog>();
}